import React from 'react';
import Head from 'next/head';
import PizzaLogo from '../assets/pizza.svg';
import { Container } from '../styles/pages/Home';

export const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <PizzaLogo />
        <h1>Hello World!</h1>
      </main>
    </Container>
  )
}

export default Home;